src/Entity/Projet.php
<?php

namespace App\Entity;

use App\Repository\ProjetRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * @ORM\Entity(repositoryClass=ProjetRepository::class)
 */
class Projet
{
    /**
     * @Groups("projet")
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Groups("projet")
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Le nom doit être renseigné",normalizer="trim")
     */
    private $nom;

    /**
     * @Groups("sous_projet")
     * @ORM\OneToMany(targetEntity=SousProjet::class, mappedBy="projet", orphanRemoval=true)
     */
    private $sousProjets;


    public function __construct()
    {
        $this->sousProjets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * @return Collection|SousProjet[]
     */
    public function getSousProjets(): Collection
    {
        return $this->sousProjets;
    }

    public function addSousProjet(SousProjet $sousProjet): self
    {
        if (!$this->sousProjets->contains($sousProjet)) {
            $this->sousProjets->add($sousProjet);

        }

        return $this;
    }

    public function removeSousProjet(SousProjet $sousProjet): self
    {
        if ($this->sousProjets->contains($sousProjet)) {
            $this->sousProjets->removeElement($sousProjet);
            // set the owning side to null (unless already changed)
            if ($sousProjet->getProjet() === $this) {
                $sousProjet->setProjet(null);
            }
        }

        return $this;
    }

    /**
     * @return float
     */
    public function getRoi():float
    {
        $coutTotal = $this->getCoutTotal();
        $prixVente = $this->getPrixVente();
        if ($coutTotal==0 || $prixVente==0)
        {
            return 0;
        }else{
            return ($coutTotal/$prixVente);
        }
    }

    function getCoutTotal()
    {
        $coutTotal =0;
        foreach ($this->getSousProjets() as $sousProjet)
        {
            $coutTotal= $coutTotal + $sousProjet->getCout();
        }
        return $coutTotal;
    }


    /**
     * @return mixed
     */
    public function getPrixVente()
    {
        $pv = 0;
        foreach ($this->getSousProjets() as $sousProjet)
        {
            $pv =$pv + $sousProjet->getPrixVente();
        }
        return $pv;
    }
    

    public function getPrixVentePrevi()
    {
        $pv = 0;
        foreach ($this->getSousProjets() as $sousProjet)
        {
            if ($sousProjet->getIsPrevisionnel())
            {
                $pv =$pv + $sousProjet->getPrixVente();
            }

        }
        return $pv;
    }
    function getCoutTotalPrevi()
    {
        $coutTotal =0;
        foreach ($this->getSousProjets() as $sousProjet)
        {
            if ($sousProjet->getIsPrevisionnel())
            {
            $coutTotal= $coutTotal + $sousProjet->getCout();
            }
        }
        return $coutTotal;
    }

    public function getRoiPrevi():float
    {
        $coutTotal = $this->getCoutTotalPrevi();
        $prixVente = $this->getPrixVentePrevi();
        if ($coutTotal==0 || $prixVente==0)
        {
            return 0;
        }else{
            return ($coutTotal/$prixVente);
        }
    }

    public function getPrixVenteNonPrevi()
    {
        $pv = 0;
        foreach ($this->getSousProjets() as $sousProjet)
        {
            if (!$sousProjet->getIsPrevisionnel())
            {
                $pv =$pv + $sousProjet->getPrixVente();
            }

        }
        return $pv;
    }
    function getCoutTotalNonPrevi()
    {
        $coutTotal =0;
        foreach ($this->getSousProjets() as $sousProjet)
        {
            if (!$sousProjet->getIsPrevisionnel())
            {
                $coutTotal= $coutTotal + $sousProjet->getCout();
            }
        }
        return $coutTotal;
    }

    public function getRoiNonPrevi():float
    {
        $coutTotal = $this->getCoutTotalNonPrevi();
        $prixVente = $this->getPrixVenteNonPrevi();
        if ($coutTotal==0 || $prixVente==0)
        {
            return 0;
        }else{
            return ($coutTotal/$prixVente);
        }
    }


}

src/Controller/ProjetController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Entity\Projet;

use DateTime;
use Detection\MobileDetect;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class ProjetController
 * @package App\Controller
 * @Route("/projet",name="projet_")
 */
class ProjetController extends AbstractController
{
    /**
     * @Route("", name="list")
     */
    public function list()
    {
        $detect = new MobileDetect();

        if ($this->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
            $projetRepo = $this->getDoctrine()->getRepository(Projet::class);
            //traitement date;
            $dateDebut = new DateTime();
            $dateDebut->setDate($dateDebut->format('Y'),$dateDebut->format('m'),1);
            $dateDebut->setTime(0,0,0);
            $dateFin = new DateTime();
            $dateFin->setDate($dateFin->format('Y'),$dateFin->format('m'),1);
            $dateFin->setTime(0,0,0);
            $dateFin->modify('+6 months');

            $filtres=[
                "categorie"=>null,
                "perio"=>null,
                "independant"=>null,
                "mot-cle"=>null,
                "previsionnel"=>"all"
            ];


            $pMensuel = $projetRepo->findByFiltres($filtres,$dateDebut,$dateFin,'MENSUEL');
            $projetRepo->clear();
            $pOneShot = $projetRepo->findByFiltres($filtres,$dateDebut,$dateFin,'ONESHOT');
            $projetRepo->clear();
            $listeVide =$this->getProjetsVide();
            krsort($pMensuel);
            krsort($pOneShot);
            $projets = array('VIDE' => $listeVide,
                'MENSUEL' => $pMensuel,
                'ONESHOT' => $pOneShot)
            ;
            //recuperation des categories
            $cateRepo = $this->getDoctrine()->getRepository(Categorie::class);
            $categories = $cateRepo->findAll();

            return $this->render('projet/projetList.html.twig', [
                'tabProjets' => $projets,
                'categories'=>$categories,
                'mobile'=>($detect->isMobile() || $detect->isTablet()),
                'page'=>'projet'
            ]);
        }
        return $this->redirectToRoute('app_login');

    }

    /**
     * @param $id
     * @param Request $request
     * @return JsonResponse|RedirectResponse
     * @Route("/{id}",name="detail",requirements={"id":"\d+"})
     */
    public function detail($id, Request $request)
    {
        if ($this->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
            if ($request->isXmlHttpRequest()) {
                $pjRepo = $this->getDoctrine()->getRepository(Projet::class);
                $pj = $pjRepo->findOneInArray($id);

                if (isset($pj)) {
                    return new JsonResponse($pj);
                } else {
                    return new JsonResponse("Projet inconnu", Response::HTTP_NOT_FOUND);
                }

            }
        }
        return $this->redirectToRoute('app_login');
    }

    /**
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @return Response
     * @Route("/update",name="update")
     */
    public function update(Request $request, EntityManagerInterface $manager)
    {
        if ($this->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
            if ($request->isXmlHttpRequest()) {
                $pjrepo = $this->getDoctrine()->getRepository(Projet::class);
                $pjInfo = json_decode($request->getContent(), true);
                dump($request->getContent());
                $pj = $pjrepo->find($pjInfo["id"]);
                if (isset($pj)) {
                    $pj->setNom($pjInfo["nom"]);
                    $manager->persist($pj);
                    $manager->flush();
                    return new JsonResponse("Modifications effectuées avec succès");
                } else {
                    return new JsonResponse("Projet inconnu", Response::HTTP_NOT_FOUND);
                }

            }
        }
        return $this->redirectToRoute('app_login');
    }

    /**
     * @param $id
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @Route("/delete/{id}",name="delete",requirements={"id":"\d+"})
     */
    public function remove($id, Request $request, EntityManagerInterface $manager)
    {
        if ($this->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
            if ($request->isXmlHttpRequest()) {
                $pjRepo = $this->getDoctrine()->getRepository(Projet::class);
                $pj = $pjRepo->find($id);
                if (isset($pj)) {
                    $manager->remove($pj);
                    $manager->flush();
                    return new JsonResponse("Suppression effectuée avec succès");
                } else {
                    return new JsonResponse("Projet inconnu", Response::HTTP_NOT_FOUND);
                }
            }
        }
        return $this->redirectToRoute('app_login');
    }


    /**
     * @param $id
     * @param Request $request
     * @Route("/prix/{type}/{id}",name="prix_type",requirements={"id":"\d+", "type":"(?:ONE SHOT|MENSUEL)"})
     */
    public function getOneByPeriodicite($type, $id, Request $request)
    {
        if ($this->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
            if ($request->isXmlHttpRequest()) {
                $pjRepo = $this->getDoctrine()->getRepository(Projet::class);
                $pj = $pjRepo->findOneByPeriodicite($id, $type);
                if (isset($pj)) {
                    return new JsonResponse($pj);
                } else {
                    return new JsonResponse('Projet inconnu', Response::HTTP_NOT_FOUND);
                }
            }
        }
        return $this->redirectToRoute('app_login');
    }


    /**
     * @Route("/insert",name="insert")
     */
    public function insert(Request $request, EntityManagerInterface $manager)
    {
        if ($this->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
            if ($request->isXmlHttpRequest()) {

                $nom = json_decode($request->getContent(), true);
                $projet = new Projet();
                $projet->setNom($nom["nom"]);
                $manager->persist($projet);
                $manager->flush();
                return new JsonResponse($projet->getId());
            }
        }
        return $this->redirectToRoute('app_login');
    }


    /**
     * @param Request $request
     * @Route("/filtre",name="filtre")
     */
    public function projetsByFiltre(Request $request)
    {
        if ($request->isXmlHttpRequest()) {
            $filtresReq = json_decode($request->getContent(), true);
            $projetRepo = $this->getDoctrine()->getRepository(Projet::class);
            //traitement date;
            $dateDebut = new DateTime();
            $dateDebut->setDate($filtresReq["year1"], $filtresReq["month1"], 1);
            $dateDebut->setTime(0,0,0,0);
            $dateFin = new DateTime();
            $dateFin->setDate($filtresReq["year2"], $filtresReq["month2"], 1);
            $dateFin->setTime(0,0,0,0);
            //chargement des listes selon periodicite
            $perio = $filtresReq["perio"];
            $listeOS=[];
            $listeM=[];
            //si filtre independant -> recuperation total heure de l'inde par projet
            $idInde = $filtresReq["independant"];
            if ($perio =="ONESHOT" || $perio==null)
            {
                $listeOS = $projetRepo->findByFiltres($filtresReq,$dateDebut,$dateFin,'ONESHOT');
                $listeOS =$this->getInfosBase($listeOS,$idInde);
            }
            if ($perio =="MENSUEL" || $perio==null)
            {
                $projetRepo->clear();
                $listeM = $projetRepo->findByFiltres($filtresReq,$dateDebut,$dateFin,'MENSUEL');
                $listeM=$this->getInfosBase($listeM,$idInde);
            }

            $projetList= [
                "MENSUEL"=>$listeM,
                "ONESHOT"=>$listeOS
            ];

            return new JsonResponse($projetList);
        }
    }

    /**
     * @param $id
     * @param Request $request
     * @return JsonResponse
     * @Route("/filtre/{id}",name="filtre_one",requirements={"id":"\d+"})
     */
    public function oneByFiltre($id,Request $request)
    {
        if ($request->isXmlHttpRequest()) {
            $filtresReq = json_decode($request->getContent(), true);
            $projetRepo = $this->getDoctrine()->getRepository(Projet::class);
            //traitement date;
            $dateDebut = new DateTime();
            $dateDebut->setDate($filtresReq["year1"], $filtresReq["month1"], 1);
            $dateDebut->setTime(0,0,0,0);
            $dateFin = new DateTime();
            $dateFin->setDate($filtresReq["year2"], $filtresReq["month2"], 1);
            $dateFin->setTime(0,0,0,0);
            //chargement des listes selon periodicite
            $perio = $filtresReq["perio"];
            //si filtre independant -> recuperation total heure de l'inde par projet
            $idInde = $filtresReq["independant"];

            if ($perio =="ONESHOT" || $perio==null)
            {
                $projetOs = $projetRepo->findOneByFiltres($filtresReq,$dateDebut,$dateFin,'ONESHOT',$id);
                if (!empty($projetOs))
                {
                    $projetOs= $this->getInfosBaseOne($projetOs[0],$idInde);
                }

            }
            if ($perio =="MENSUEL" || $perio==null)
            {
                $projetRepo->clear();
                $projetM = $projetRepo->findOneByFiltres($filtresReq,$dateDebut,$dateFin,'MENSUEL',$id);
                if (!empty($projetM)) {

templates/projet/ficheInde.html.twig
<div id="fiche-inde" class="row mr-3 ml-3 mt-5 justify-content-center w-auto" style="display: none">
    {%  if not mobile %}
    <div>
    {%  endif %}
    <h3 class="mb-3 text-primary mt-1" id="nom-inde-periode">Pierre Machin</h3>
{%  if mobile %}
        <div class="row w-100">
            <div class="col">
{%  endif %}
        <div class="input-group input-group-sm mb-3  ml-1 w-auto" >
            <div class="input-group-prepend">
                <p class="input-group-text w-auto h-auto">Nombres d'heures : </p>
            </div>
            <p id="heure-periode" class="form-control input-filtres w-auto h-auto">35H</p>
        </div>

        <div class="input-group input-group-sm mb-3 ml-1 w-auto">
            <div class="input-group-prepend">
                <p class="input-group-text w-auto h-auto">Nombres de missions : </p>
            </div>
            <p id="nb-projets-periode" class="form-control input-filtres w-auto h-auto">35H</p>
        </div>
        {%  if mobile %}
            </div>
            <div class="col">
        {%  endif %}
        <div class="input-group input-group-sm mb-3  ml-1  w-auto h-auto">
            <div class="input-group-prepend">
                <p class="input-group-text  w-auto h-auto">Coût Total : </p>
            </div>
            <p id="cout-periode" class="form-control input-filtres  w-auto h-auto">500 €</p>
        </div>
        <div class="input-group input-group-sm mb-3  ml-1  w-auto h-auto">
            <div class="input-group-prepend">
                <p class="input-group-text  w-auto h-auto">Prix de vente : </p>
            </div>
            <p id="pv-periode" class="form-control input-filtres  w-auto h-auto">500 €</p>
        </div>
                {%  if mobile %}
            </div>
            <div class="col">
                {%  endif %}
        <div class="input-group input-group-sm mb-3  ml-1  w-auto h-auto">
            <div class="input-group-prepend">
                <p class="input-group-text  w-auto h-auto">Ratio : </p>
            </div>
            <p id="ratio-periode" class="form-control input-filtres  w-auto h-auto">30 %</p>
        </div>

        {%  if mobile %}
            </div>
        {%  endif %}

        </div>



        </div>

templates/projet/filtre.html.twig
<div id="filtres" class="row mr-3 justify-content-center"
     {%  if mobile %}
        data-mobile="true"
     {% else %}
     data-mobile="false"
     {%  endif %}
     data-categorie="null"
     data-perio="null"
     data-independant="null"
     data-mot-cle="null"
     data-month1="{{ "now" | date("m") }}"
     data-year1="{{ "now" | date("Y") }}"
     data-month2="{{ "now + 3month" | date("m") }}"
     data-year2="{{ "now" | date("Y") }}"
     data-previsionnel="all"
>
    <div class="col"></div>
    <div class="col-11"
    >
    <form class="form-inline w-100" id="form-filtre">

            <h1 class="text-center w-100 mb-3 text-primary">Filtres</h1>

            <div class="input-group input-group-sm mb-3">
                <div class="input-group-prepend">
                    <label for="categorie" class="input-group-text w-100" id="cate-label">Catégorie</label>
                </div>
                <select id="categorie" class="custom-select input-filtres">
                    <option value="0">Toutes les catégorie</option>
                </select>
            </div>


            <div class="input-group input-group-sm mb-3">
                <div class="input-group-prepend">
                    <label for="perio" class="input-group-text">Périodicité</label>
                </div>
                <select id="perio"  class="form-control custom-select mb-3 input-filtres">
                    <option value="0">Toutes les périodicités</option>
                </select>
            </div>


            <div class="input-group input-group-sm mb-3 ">
                <div class="input-group-prepend">
                    <label for="inde" class="input-group-text">Indépendant</label>
                </div>
                <select id="inde"  class="form-control custom-select input-filtres">
                    <option value="0">Tous les indépendant</option>
                </select>
            </div>

        <div class="input-group input-group-sm mb-3 ">
            <div class="input-group-prepend">
                <label for="previ" class="input-group-text">Prévisionnel</label>
            </div>
            <select id="previsionnel"  class="form-control custom-select input-filtres">
                <option value="all" selected>Tout afficher</option>
                <option value="non-previ">Projets vendus</option>
                <option value="previ" >Projets prévisionnel</option>
            </select>
        </div>


            <div class="input-group input-group-sm mb-3">
                <div class="input-group-prepend">
                    <label for="mot-cle" class="input-group-text">Recherche</label>
                </div>
                <input type="text" placeholder="Recherche par mots-clés" id="mot-cle" class="form-control w-auto input-filtres">
            </div>

            <div class="input-group input-group-sm mb-3" >
                <div class="input-group input-group-sm">
                <div class="input-group-prepend ">
                    <span class="input-group-text w-auto">Du</span>
                </div>
                    <div class="input-group input-group-sm" >
                <select id="month-begin"  class="form-control custom-select" style="width: min-content">
                    <option>{{ "now" | date("m") }}</option>
                </select>
                <select id="year-begin" class="form-control custom-select"style="width: min-content">
                    <option>{{ "now" | date("y") }}</option>
                </select>
                    </div>
                </div>
                <div class="input-group input-group-sm">
                <div class="input-group-prepend">
                    <span class="input-group-text w-auto">Au</span>
                </div>
                    <div class="input-group input-group-sm">
                <select id="month-end"  class="form-control custom-select" style="width: min-content">
                    <option>{{ "now + 3month" | date("m") }}</option>
                </select>
                <select id="year-end"  class="form-control custom-select  input-filtres" style="width: min-content">
                    <option>{{ "now" | date("y") }}</option>
                </select>
                    </div>
                </div>
            </div>
            <div class="">
                <button class="btn btn-primary mb-3 mr-3" id="filtrer" type="submit">Filtrer</button>

                <button class="btn btn-primary mb-3" id="3months">Afficher les 3 prochains mois</button>
            </div>

        {% if is_granted("ROLE_ADMIN") == true %}
            <div>

                <input type="checkbox" id="visiPrix"/>Masquer les prix
            </div>

            <div class="js-user-admin" data-is-admin="true"></div>
            <div class="js-user-user" data-is-user="false"></div>
            
        {% endif %}
        {% if is_granted("ROLE_USER") == true %}
           
            <div>

                <input type="checkbox" id="visiPrix" checked="checked" style="display:none"/>
            </div>
            <div class="js-user-admin" data-is-admin="false"></div>
            <div class="js-user-user" data-is-user="true"></div>
        
        {% endif %}
        {% if is_granted("ROLE_RESPONSABLE") == true %}
        <div>

                <input type="checkbox" id="visiPrix" checked="checked" style="display:none"/>
            </div>
            <div class="js-user-admin" data-is-admin="false"></div>
            <div class="js-user-user" data-is-user="false"></div>
            
        
        {% endif %}


    </form>
    </div>
    <div class="col"></div>
</div>

templates/projet/globalCate.html.twig
<div id="global-cate" class="container-fluid m-2 justify-content-center w-auto" style="display: none">
    <h3 class="mb-4 text-primary mt-1" id="titre-global-cate">Catégories </h3>
    <div class="form-inline">
    {%  for categorie in categories %}
        <div class="form-inline justify-content-start mr-2" id="ligne-{{ categorie.id }}">
            <div class="input-group" input-group-sm  >
                <div class="input-group input-group-sm mb-2">
                    <p class="mr-2 titre-infos">
                        {%  if categorie.libelle =='Prestations de conseils' %}
                            Prestations
                        {%  else %}
                            {{ categorie.libelle | capitalize }}
                        {%  endif %}
                    </p>
                </div>
                <div class="input-group input-group-sm mb-2">
                    <div class="input-group input-group-sm mb-2">
                        <div class="input-group-prepend ">
                            <span class="input-group-text  h-auto">PV</span>
                        </div>
                        <span id="pv_cate_{{ categorie.id }}" class="form-control form-control-sm input-filtres money-text w-auto h-auto">15000 €</span>
                    </div>
                    <div class="input-group input-group-sm ml-1 mb-2">
                        <div class="input-group-prepend">
                            <span class="input-group-text  h-auto">ROI</span>
                        </div>
                        <span id="roi_cate_{{ categorie.id }}" class="form-control input-filtres w-auto percent-text h-auto">36 %</span>
                    </div>
                </div>
            </div>
        </div>
    {%  endfor %}
    </div>
</div>

templates/projet/spj.html.twig
<table class="sousProjets table table-sm table-borderless">
    <thead>
    <tr>
        <th colspan="2">
            <button title="Ajouter un sous-projet" class="bouton btn btn-add-spj">
                <svg class="bi bi-plus-circle" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">em
                    <path fill-rule="evenodd" d="M8 3.5a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-.5.5H4a.5.5 0 0 1 0-1h3.5V4a.5.5 0 0 1 .5-.5z"/>
                    <path fill-rule="evenodd" d="M7.5 8a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1H8.5V12a.5.5 0 0 1-1 0V8z"/>
                    <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                </svg>
            </button>
            Désignation</th>
        <th>Catégorie</th>
        <th>PV</th>
        <th>ROI</th>
    </tr>
    </thead>
    <tbody>
    {% for spj in projet.sousProjets %}

        <tr style="border-top: #0b2e13 solid 1px">
            <td></td>
            <td>{{ spj.designation }}</td>
            <td>{{  spj.categorie.libelle }}</td>
            <td>{{  spj.prixVente }} €</td>
            <td>{{  spj.roi  | number_format(2,',',' ')}}</td>
            <td>
                <span>
                    <button class="btn btn-mdf-spj button">Modifier</button>
                    <button class="btn button btn-sup-spj">Supprimer</button>
                    <button class="btn btn-dplq">Dupliquer</button>
                </span>
            </td>
        </tr>
        <tr>
            <th colspan="2">
                <button title="Ajouter une prestation" class="bouton btn btn-add-presta">
                    <svg class="bi bi-plus-circle" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M8 3.5a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-.5.5H4a.5.5 0 0 1 0-1h3.5V4a.5.5 0 0 1 .5-.5z"/>
                        <path fill-rule="evenodd" d="M7.5 8a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1H8.5V12a.5.5 0 0 1-1 0V8z"/>
                        <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                    </svg>
                </button>

                Autres prestations</th>
            {%  if spj.autrePrestations is not empty %}
                {%  for autrePresta in spj.autrePrestations %}
                    <td>{{ autrePresta.detail}} </td>
                    <td>{{ autrePresta.montant}} €</td>
                    <td>
                                                    <span>
                                                        <button class="btn btn-mdf-spj button">Modifier</button>
                                                        <button class="btn button btn-sup-spj">Supprimer</button>
                                                    </span>
                    </td>
                {%  endfor %}
            {%  endif %}
        </tr>
        <tr>
        <th colspan="2">
        <button title="Ajouter un indépendant" class="bouton btn btn-add-inde">
            <svg class="bi bi-plus-circle" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M8 3.5a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-.5.5H4a.5.5 0 0 1 0-1h3.5V4a.5.5 0 0 1 .5-.5z"/>
                <path fill-rule="evenodd" d="M7.5 8a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1H8.5V12a.5.5 0 0 1-1 0V8z"/>
                <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
            </svg>
        </button>
        {% if spj.heures is  not empty %}
            Indépendant</th>
            <th>Coût</th>
            <th></th>
            <th></th>
            </tr>
            {%  for heure in spj.heures %}
                <tr>
                    <td></td>
                    <td>{{  heure.independant.prenom }}</td>
                    <td>{{ heure.heure * heure.independant.salaire}}€</td>
                    <td>
                        {{ heure.commentaire }}
{#                            <input id="commentaire" name="commentaire" value="" >#}
                    </td>
                    <td>
                        <span>
                            <button class="btn btn-mdf-inter button">Modifier</button>
                            <button class="btn button btn-sup-inter">Supprimer</button>
                        </span>
                    </td>
                </tr>
            {%  endfor %}
        {%  else %}
            Aucun indépendant</th>
        {%  endif %}
    {% endfor %}
    </tbody>
</table>